#version 460

layout(binding = 0, set = 0, rgba16f) uniform readonly image2D last_image;
layout(binding = 1, set = 0, rgba16f) uniform image2D new_image;

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main() {
    vec4 last = imageLoad(last_image, ivec2(gl_GlobalInvocationID.xy));
    vec4 new = imageLoad(new_image, ivec2(gl_GlobalInvocationID.xy));
    float t = 0.6;
    vec4 blend = last * 0.92;
    imageStore(new_image, ivec2(gl_GlobalInvocationID), blend);
}